import { Meal } from "@/context/MealContext";
import * as crypto from "expo-crypto";

export const mealSeed: Meal[] = [
  {
    id: crypto.randomUUID(),
    name: "Grilled Chicken & Rice",
    calories: 520,
    protein: 45,
    carbs: 55,
    fat: 8,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Salmon with Sweet Potato",
    calories: 480,
    protein: 38,
    carbs: 42,
    fat: 14,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Beef Stir Fry with Noodles",
    calories: 620,
    protein: 35,
    carbs: 68,
    fat: 18,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Greek Yogurt & Oats",
    calories: 340,
    protein: 22,
    carbs: 48,
    fat: 6,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Egg & Avocado Toast",
    calories: 410,
    protein: 18,
    carbs: 35,
    fat: 22,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Turkey & Veggie Wrap",
    calories: 450,
    protein: 32,
    carbs: 48,
    fat: 12,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Tuna Pasta Salad",
    calories: 490,
    protein: 34,
    carbs: 52,
    fat: 10,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Cottage Cheese & Berries",
    calories: 280,
    protein: 24,
    carbs: 30,
    fat: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Lentil & Vegetable Soup",
    calories: 360,
    protein: 20,
    carbs: 58,
    fat: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: crypto.randomUUID(),
    name: "Shrimp & Quinoa Bowl",
    calories: 430,
    protein: 36,
    carbs: 44,
    fat: 9,
    createdAt: new Date().toISOString(),
  },
];
